// Generated from api/transcript-view-v1.schema.json. Do not edit by hand.
export type TranscriptJsonPrimitive = string | number | boolean | null;
export type TranscriptJsonValue = TranscriptJsonPrimitive | TranscriptJsonObject | ReadonlyArray<TranscriptJsonValue>;
export type TranscriptJsonObject = { readonly [key: string]: TranscriptJsonValue };
export type TranscriptEmptyObject = { readonly [key: string]: never };
export const TRANSCRIPT_VIEW_SCHEMA_SHA256 = "301f1c9457434d3c6ed1c663cc33ba9ca41b1f0da35621792dae5c1dd205e326" as const;

export type TranscriptSource = { "kind": "assistant_message" | "tool_input" | "tool_result"; "id": string; "index": 0; "stream": "none" } | { "kind": "tool_output"; "id": string; "index": number; "stream": "stdout" | "stderr" | "result" | "diagnostic" };
export type TranscriptChunk = { "index": number; "offsetBytes": number; "artifactId": string; "sizeBytes": number; "sha256": string };
export type TranscriptManifest = { "schemaId": "transcript-view-v1"; "nodeId": string; "dialogId": string; "attemptId": string; "generation": number; "textId": string; "source": { "kind": "assistant_message" | "tool_input" | "tool_result"; "id": string; "index": 0; "stream": "none" } | { "kind": "tool_output"; "id": string; "index": number; "stream": "stdout" | "stderr" | "result" | "diagnostic" }; "preview": string; "previewTruncated": boolean; "redaction": "none" | "applied"; "sizeBytes": number; "sha256": string; "complete": true; "chunks": ReadonlyArray<{ "index": number; "offsetBytes": number; "artifactId": string; "sizeBytes": number; "sha256": string }> } | { "schemaId": "transcript-view-v1"; "nodeId": string; "dialogId": string; "attemptId": string; "generation": number; "textId": string; "source": { "kind": "assistant_message" | "tool_input" | "tool_result"; "id": string; "index": 0; "stream": "none" } | { "kind": "tool_output"; "id": string; "index": number; "stream": "stdout" | "stderr" | "result" | "diagnostic" }; "preview": string; "previewTruncated": boolean; "redaction": "none" | "applied"; "sizeBytes": number; "sha256": string; "complete": false; "reason": "output_limit_exceeded"; "chunks": ReadonlyArray<{ "index": number; "offsetBytes": number; "artifactId": string; "sizeBytes": number; "sha256": string }> };
export type TranscriptProjectionFixture = { "schemaId": "transcript-view-v1"; "candidates": ReadonlyArray<{ "source": "delta" | "final" | "history" | "replica"; "messageId": string; "attemptId": string; "generation": number; "revision": number; "textHash": string; "text": string; "final": boolean }>; "expected": ReadonlyArray<{ "messageId": string; "attemptId": string; "generation": number; "textHash": string; "text": string; "final": boolean; "sources": ReadonlyArray<"delta" | "final" | "history" | "replica"> }> };
